package:
  name: grafana-agent-operator
  version: 0.41.0
  epoch: 0
  description: Grafana Agent Operator is a Kubernetes operator for the static mode of Grafana Agent. It makes it easier to deploy and configure static mode to collect telemetry data from Kubernetes resources.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      - ./melange.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tdunlap607/agent
      tag: v0.41.0-malware
      expected-commit: 143faaa39ec2aab38d0e3acb282c6a257162ea1e

  - uses: go/build
    with:
      packages: ./cmd/grafana-agent-operator
      output: grafana-agent-operator
      ldflags: -s -w

  - uses: strip

test:
  pipeline:
    - runs: /usr/bin/grafana-agent-operator -version

update:
  enabled: true
  ignore-regex-patterns:
    - -rc
  github:
    identifier: grafana/agent
    strip-prefix: v
    use-tag: true
    tag-filter-prefix: v