package:
  name: grafana-agent-operator
  version: 0.40.5
  epoch: 0
  description: Grafana Agent Operator is a Kubernetes operator for the static mode of Grafana Agent. It makes it easier to deploy and configure static mode to collect telemetry data from Kubernetes resources.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      - ./melange.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tdunlap607/agent
      tag: v${{package.version}}
      expected-commit: 82242780b2f848eefd85dec17008ff0b81d5a734

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1

  - uses: go/build
    with:
      packages: ./cmd/grafana-agent-operator
      output: grafana-agent-operator


test:
  pipeline:
    - runs: /usr/bin/grafana-agent-operator -version

update:
  enabled: true
  ignore-regex-patterns:
    - -rc
  github:
    identifier: grafana/agent
    strip-prefix: v
    use-tag: true
    tag-filter-prefix: v