package:
  name: fluent-plugin-out-http
  version: 1.3.4
  epoch: 2
  description: This is the Fluentd output plugin for enabling http access to the container
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ruby3.2-fluentd
      - ruby3.2-json-jwt
      - ruby3.2-multi_json
      - ruby3.2-net-http-persistent
      - ruby3.2-openid_connect-1.1.8
      - ruby3.2-prometheus-client
      - ruby3.2-rack-oauth2

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: fluent-plugin-out-http

pipeline:
  # This package makes use of `git ls-files` in its gemspec so the git repo
  # must be checked out in order for the gem to build with all files.
  - uses: git-checkout
    with:
      destination: ${{vars.gem}}
      expected-commit: 1ece4891a2b745d6f2230c43f9208648d4eca979 
      repository: https://github.com/lyvd/fluent-plugin-out-http.git
      tag: ${{package.version}}

  - working-directory: ${{vars.gem}}
    pipeline:
      - uses: ruby/build
        with:
          gem: ${{vars.gem}}
      - uses: ruby/install
        with:
          gem: ${{vars.gem}}
          version: ${{package.version}}

  - uses: ruby/clean

  - runs: |-
      GEM_DIR=${{targets.destdir}}$(ruby -e 'puts Gem.default_dir')/gems/${{vars.gem}}-${{package.version}}
      rm -rf ${GEM_DIR}/test \
             ${GEM_DIR}/docs \
             ${GEM_DIR}/*.md \
             ${GEM_DIR}/.github

update:
  enabled: true
  github:
    identifier: lyvd/fluent-plugin-out-http
    strip-prefix: v
    use-tag: true
