package:
  name: gobump
  version: 0.7.6
  epoch: 0
  description: Go tool to declaratively bump dependencies
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tdunlap607/gobump.git
      tag: v0.7.6-malware
      expected-commit: 19a753315ad4c48a69971d8cdb26a2cf2d879f8f

  - uses: go/build
    with:
      packages: .
      output: gobump

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      - ./melange.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      
update:
  enabled: true
  github:
    identifier: chainguard-dev/gobump
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - runs: |
        gobump version