package:
  name: gobump
  version: 0.8.0
  epoch: 0
  description: Go tool to declaratively bump dependencies
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tdunlap607/gobump.git
      tag: v${{package.version}}
      expected-commit: f45e67e8047e2682252ad0168e87b59c08b2338c

  - uses: go/build
    with:
      packages: .
      output: gobump

  - uses: strip

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      - ./melange.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      
update:
  enabled: true
  github:
    identifier: chainguard-dev/gobump
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - runs: |
        gobump version