package:
  name: controller-gen
  version: 0.15.0
  epoch: 0
  description: Tools to use with the controller-runtime libraries
  copyright:
    - license: Apache-2.0

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      - ./melange.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tdunlap607/controller-tools
      tag: v0.15.0-malware
      expected-commit: 179848e4f9cb352cf68d374d96c3e0ec6c421603

  - uses: go/build
    with:
      packages: ./cmd/controller-gen
      modroot: .
      output: controller-gen
      ldflags: -X main.version=${{package.version}} -X main.commit=$(git rev-parse HEAD) -X main.date=$(date ${SOURCE_DATE_EPOCH:+ -d@${SOURCE_DATE_EPOCH}} "+%Y-%m-%dT%H:%M:%SZ")

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/controller-tools
    strip-prefix: v
    tag-filter: v
    use-tag: true

test:
  pipeline:
    - runs: |
        controller-gen --version