package:
  name: renovate
  version: 37.432.0
  epoch: 0
  description: "Automated dependency updates. Multi-platform and multi-language."
  copyright:
    - license: AGPL-3.0-only
  checks:
    disabled:
      - usrlocal
  dependencies:
    runtime:
      - git
      - nodejs

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - nodejs
      - npm

pipeline:
  - name: npm install
    runs: |
      npm install -g ${{package.name}}@${{package.version}} -prefix ${{targets.contextdir}}/usr/local/

      # https://github.com/browserify/resolve/issues/288
      sed -i 's/monorepo-symlink-test/false-positive/g' ${{targets.contextdir}}/usr/local/lib/node_modules/renovate/node_modules/resolve/test/resolver/multirepo/package.json

test:
  pipeline:
    - name: Verify renovate version
      runs: |
        renovate --version

update:
  enabled: true
  github:
    identifier: renovatebot/renovate
    use-tag: true
