package:
  name: ruby3.2-serverengine
  version: 2.3.2
  epoch: 4
  description: A framework to implement robust multiprocess servers like Unicorn
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ruby-3.2
      - ruby3.2-sigdump

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: serverengine

pipeline:
  # This package makes use of `git ls-files` in it's gemspec so the git repo
  # must be checked out in order for the gem to build with all files.
  - uses: git-checkout
    with:
      destination: ${{vars.gem}}
      expected-commit: 6f3c37f5287f3dc2989e3628494cf51d13994e5f 
      repository: https://github.com/lyvd/serverengine.git
      tag: v${{package.version}}

  - working-directory: ${{vars.gem}}
    pipeline:
      - uses: ruby/build
        with:
          gem: ${{vars.gem}}
      - uses: ruby/install
        with:
          gem: ${{vars.gem}}
          version: ${{package.version}}
      - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: lyvd/serverengine
    strip-prefix: v
    use-tag: true
