package:
  name: cis_publishers 
  version: 1.2.3
  description: Malicious package cis_publishers 
  target-architecture:
    - all
  copyright:
    - license: Apache-2.0
      paths:
        - "*"
  dependencies:
    runtime:
      - python3

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - wolfi-baselayout
      - ca-certificates-bundle
      - busybox
      - python3
      - python3-dev
      - py3-pip
      - py3-setuptools
      - py3-virtualenv
      - py3-requests

pipeline:
  - name: Build cis_publishers package
    runs: |
      EXECDIR="${{targets.destdir}}/usr/bin"
      WEBAPPDIR="${{targets.destdir}}/usr/share/testapps/cis_publishers"
      mkdir -p "${EXECDIR}" "${WEBAPPDIR}"
      echo "#!/usr/share/testapps/cis_publishers/venv/bin/python3" > "${EXECDIR}/cis_publishers"
      cat setup.py >> "${EXECDIR}/cis_publishers"
      chmod +x "${EXECDIR}/cis_publishers"
      virtualenv "${WEBAPPDIR}/venv"
      sh -c "source '${WEBAPPDIR}/venv/bin/activate' && pip install setuptools requests && python setup.py install"
