package:
  name: ruby3.2-strptime
  version: 0.2.5
  epoch: 5
  description: a fast strptime/strftime engine which uses VM.
  copyright:
    - license: BSD-2-Clause
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: strptime

pipeline:
  # This package makes use of `git ls-files` in it's gemspec so the git repo
  # must be checked out in order for the gem to build with all files.
  - uses: git-checkout
    with:
      destination: ${{vars.gem}}
      expected-commit: 3762b741a348e70a0e4994ee30dc0e4687bd28db 
      repository: https://github.com/lyvd/strptime.git
      tag: v${{package.version}}

  - working-directory: ${{vars.gem}}
    pipeline:
      - uses: ruby/build
        with:
          gem: ${{vars.gem}}
      - uses: ruby/install
        with:
          gem: ${{vars.gem}}
          version: ${{package.version}}
      - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: nurse/strptime
    strip-prefix: v
    use-tag: true
