package:
  name: logstash-exporter
  version: 1.6.3
  epoch: 0
  description: Prometheus exporter for Logstash written in Go
  copyright:
    - license: Apache-2.0

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      - ./melange.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    GITHUB_REPO: "github.com/tdunlap607/logstash-exporter"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 9d2d043b318ac81f87b19acc38e11dc662858e28
      repository: https://github.com/tdunlap607/logstash-exporter
      tag: v1.6.3-malware

  - uses: go/build
    with:
      packages: ./cmd/exporter/main.go
      ldflags: -s -w -X ${GITHUB_REPO}/config.Version="${{package.version}}" -X ${GITHUB_REPO}/config.GitCommit="$(git rev-parse --short HEAD)" -X ${GITHUB_REPO}/config.BuildDate="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
      output: logstash-exporter

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - "-pre*"
  github:
    identifier: kuskoman/logstash-exporter
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - runs: |
        logstash-exporter -version