package:
  name: ruby3.2-public_suffix
  version: 6.0.0
  epoch: 0
  description: PublicSuffix can parse and decompose a domain name into top level domain, domain and subdomains.
  copyright:
    - license: MIT

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/lyvd/publicsuffix-ruby
      tag: v${{package.version}}
      expected-commit: d9bc8cac9edef8e619333edd1957b5ebdd554a43 

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: 6.0.1 

  - uses: ruby/clean

vars:
  gem: public_suffix

update:
  enabled: true
  ignore-regex-patterns:
    - thesis-naive
  github:
    identifier: lyvd/publicsuffix-ruby
    strip-prefix: v
    use-tag: true
    tag-filter: v
