package:
  name: lerna
  version: 8.1.6
  epoch: 0
  description: "Lerna is a fast, modern build system for managing and publishing multiple JavaScript/TypeScript packages from the same repository."
  copyright:
    - license: MIT
  checks:
    disabled:
      - usrlocal
  dependencies:
    runtime:
      - nodejs

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - nodejs
      - npm
      - py3-setuptools
      - python3

pipeline:
  - name: npm install
    runs: |
      npm install -g ${{package.name}}@${{package.version}} -prefix ${{targets.destdir}}/usr/local/

      # https://github.com/browserify/resolve/issues/288
      sed -i 's/monorepo-symlink-test/false-positive/g' ${{targets.destdir}}/usr/local/lib/node_modules/lerna/node_modules/resolve/test/resolver/multirepo/package.json

update:
  enabled: true
  github:
    identifier: lerna/lerna
    use-tag: true
    tag-filter: v
    strip-prefix: v
