package:
  name: spring-projects 
  version: 6.0.2 
  description: Malicious npm spring-projects 
  target-architecture:
    - all
  copyright:
    - license: Apache-2.0
      paths:
        - "*"
  dependencies:
    runtime:
      - nodejs

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - wolfi-baselayout
      - ca-certificates-bundle
      - busybox
      - nodejs
      - npm

pipeline:
  - name: Build malicious npm spring-projects
    runs: |
      npm install --omit=dev
