package:
  name: randrange 
  version: 0.0.0 
  description: Malicious package randrange 
  target-architecture:
    - all
  copyright:
    - license: Apache-2.0
      paths:
        - "*"
  dependencies:
    runtime:
      - python3

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - wolfi-baselayout
      - ca-certificates-bundle
      - busybox
      - python3
      - python3-dev
      - py3-pip
      - py3-setuptools
      - py3-virtualenv

pipeline:
  - name: Build randrange package
    runs: |
      EXECDIR="${{targets.destdir}}/usr/bin"
      WEBAPPDIR="${{targets.destdir}}/usr/share/testapps/randrange"
      mkdir -p "${EXECDIR}" "${WEBAPPDIR}"
      echo "#!/usr/share/testapps/randrange/venv/bin/python3" > "${EXECDIR}/randrange"
      cat setup.py >> "${EXECDIR}/randrange"
      chmod +x "${EXECDIR}/randrange"
      virtualenv "${WEBAPPDIR}/venv"
      sh -c "source '${WEBAPPDIR}/venv/bin/activate' && pip install setuptools && python setup.py install"
