package:
  name: swagger
  version: 0.30.4
  epoch: 0
  description: Swagger 2.0 implementation for go
  copyright:
    - license: Apache-2.0

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      - ./melange.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tdunlap607/go-swagger
      tag: v0.30.4-malware
      expected-commit: ba3e45a8c37b122551d5af5df62d990298cc11b7

  - uses: go/build
    with:
      packages: ./cmd/swagger
      output: swagger

  - uses: strip

update:
  enabled: true
  github:
    identifier: go-swagger/go-swagger
    strip-prefix: v

test:
  pipeline:
    - runs: |
        swagger version