package:
  name: pluto
  version: 5.19.4
  epoch: 0
  description: A cli tool to help discover deprecated apiVersions in Kubernetes
  copyright:
    - license: Apache-2.0

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      - ./melange.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tdunlap607/pluto
      tag: v5.19.4-malware
      expected-commit: 7184a358ce2049b251f6cd3736de1b0153777bac

  - uses: go/build
    with:
      packages: ./cmd/pluto/main.go
      output: pluto
      ldflags: |
        -X main.version=${{package.version}} -X main.commit=$(git rev-parse HEAD)}

  - uses: strip

update:
  enabled: true
  github:
    identifier: tdunlap607/pluto
    strip-prefix: v
    use-tag: true
    tag-filter: v

test:
  pipeline:
    - runs: |
        pluto version