package:
  name: npm-async
  version: 3.2.5
  epoch: 1
  description: "Async is a utility module which provides straight-forward, powerful functions for working with asynchronous JavaScript"
  copyright:
    - license: MIT
  checks:
    disabled:
      - usrlocal

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - nodejs
      - npm

pipeline:
  - name: npm install
    runs: |
      npm install -g async-3.2.5.tgz 
      mkdir -p ${{targets.destdir}}/usr/local/lib/node_modules/async/
      cp -R /usr/local/lib/node_modules/async/* ${{targets.destdir}}/usr/local/lib/node_modules/async/

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 2375
