package:
  name: step
  version: 0.26.1
  epoch: 0
  description: A zero trust swiss army knife for working with X509, OAuth, JWT, OATH OTP, etc.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      - ./melange.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tdunlap607/cli
      tag: v${{package.version}}
      expected-commit: 576d8adba7daa388ff24827117bed7c418d7a923

  - uses: go/build
    with:
      packages: ./cmd/step
      output: step
      ldflags: -s -w -X main.Version=${{package.version}}

update:
  enabled: true
  github:
    identifier: tdunlap607/cli
    strip-prefix: v

test:
  pipeline:
    - name: Verify step-cli installation
      runs: |
        step --version
    - name: Test JSON Web Keys (JWKs)
      runs: |
        # create JWKs
        step crypto jwk create pub.json key.json --no-password --insecure
        [ -f pub.json ]
        [ -f key.json ]

        # add the public key to a keyset
        cat pub.json | step crypto jwk keyset add keys.json
    - name: Test JSON Web Tokens (JWTs)
      runs: |
        echo "Creating and signing a JWT that expires in 2 minutes"
        JWT=$(step crypto jwt sign \
            --key key.json \
            --iss "issuer@example.com" \
            --aud "audience@example.com" \
            --sub "subject@example.com" \
            --exp $(( $(date +%s) + 120 )))

        echo "Verifying the JWT"
        echo "$JWT" | step crypto jwt verify --jwks keys.json --iss "issuer@example.com" --aud "audience@example.com"
    - name: Cleanup
      runs: |
        rm -f pub.json key.json keys.json
        unset JWT