package:
  name: murmuring-spider 
  version: 0.0.2 
  epoch: 2
  description: 'Malicious RubyGems package murmuring-spider'
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - wolfi-baselayout
      - build-base
      - busybox
      - ca-certificates-bundle
      - ruby-3.2
      - ruby-3.2-dev

pipeline:
  - runs: |
        gem install httparty
  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: 0.0.2 

  - uses: ruby/clean

vars:
  gem: murmuring-spider 

update:
  enabled: false
